### ISSUE TITLE
"Tertirary" vs "Tertiary"

### ISSUE THREAD

**Issue by didoo** [JB1905/react-figma-ui#13]
In the original `figma-plugin-ds` repo the classname for the "tertiary" button is `tertiary` (even though there is a `tertirary` in the Readme.md, which maybe caused this problem) while in this repo the "tint" value used (and also declared in the TypeScript definition and across the tests) is `tertirary` (so, with a typo).

This also doesn't style correctly the button, since the className used is wrong.

If it's OK for you, I can create a PR to fix this.

**Comment by JB1905** [comment]
Thanks for your issue 😃
I will fix this bug later today.

**Comment by JB1905** [comment]
Please check `1.0.0-beta.12`

**Comment by didoo** [comment]
@JB1905 yes, with `1.0.0-beta.12` is fixed
