### ISSUE TITLE
Tab Component

### ISSUE THREAD

**Issue by ViniCleFer** [JB1905/react-figma-ui#34]
Do you know any lib that has a tab component and that works with that?

**Comment by JB1905** [comment]
Hi!
You can check [figma-styled-components](https://figma-styled-components.netlify.app/?path=/docs/mdx-tabs--tabs) or [other similar libraries](https://github.com/JB1905/react-figma-ui#alternatives). I want to stick available components to `figma-plugin-ds` styles. If you want, you can create own component using CSS variables from `figma-plugin-ds`.

**Comment by ViniCleFer** [comment]
Ok, Thank You, I create own component using CSS variables from `figma-plugin-ds`
